export { default as HeroSection } from './HeroSection.vue'
export { default as AboutSection } from './AboutSection.vue'
export { default as ServicesSection } from './ServicesSection.vue'
export { default as StatisticsSection } from './StatisticsSection.vue'
export { default as TestimonialsSection } from './TestimonialsSection.vue'
export { default as CareerSection } from './CareerSection.vue'
export { default as ContactSection } from './ContactSection.vue'
export { default as ContactFormSection } from './ContactFormSection.vue'
export { default as FAQSection } from './FAQSection.vue'

// About page specific sections
export { default as AboutHeroSection } from './AboutHeroSection.vue'
export { default as CompanyStorySection } from './CompanyStorySection.vue'
export { default as MissionVisionSection } from './MissionVisionSection.vue'
export { default as TeamSection } from './TeamSection.vue'
export { default as ValuesSection } from './ValuesSection.vue'
export { default as ContactCTASection } from './ContactCTASection.vue'
export { default as OurClientsSection } from './OurClientsSection.vue'